# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73a4dba17113d486f65686a5b9d396a1dfb3c908158a9ca2aea939d645ad336fd2924a8ab7fa28a5aca147d75b602ed1e7aa7cb0139fa4b1076b6040256cd2e2

test:
  secret_key_base: 836d53e4056bbe173091c49283c29f6229be0ad3fbae154bb3e0a4b7282a6c3c9a6a5abba9e1c3a5018e8f7b95e626b424c21785ba0dbe52b4a8b792cc14db11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
